version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27521:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cinema
    volumes:
      - ./provisioning/:/docker-entrypoint-initdb.d/
  cinema:
    image: cinema
    environment:
      omdb.apiKey: ${OMDB_APIKEY}
    ports:
      - 8080:8080
    depends_on:
      - mongo